### ISSUE TITLE
Noscript Chrome extension 12.0.7 not compatible with Kiwi Browser.

### ISSUE THREAD

**Issue by possom2009** [hackademix/noscript#398]
After the extension updated for Chrome, all sites are blank unless the extension is disabled.

**Comment by C-O-D** [comment]
Can confirm, 11.4.44 on the other hand does work...

**Comment by hackademix** [comment]
What does the console say?
Have you got other extensions which may block local network requests, e.g. uBlock, and does disabling them temporarily help?

**Comment by C-O-D** [comment]
Do you mean something like this?

![Screenshot_com kiwibrowser browser dev](https://github.com/user-attachments/assets/8accafd4-ce7e-4c78-88b7-8d40f0749429)

**Comment by C-O-D** [comment]
I disabled uBlock which didn't help...

**Comment by possom2009** [comment]
> What does the console say? Have you got other extensions which may block local network requests, e.g. uBlock, and does disabling them temporarily help?

Problem still occurs after disabling uBlock. Here's what the console says.

![screenshot](https://github.com/user-attachments/assets/c47ab992-a557-4e51-b3f9-47bc471c6f8b)

**Comment by hackademix** [comment]
Which Chrome version are you using?

**Comment by C-O-D** [comment]
![Screenshot_2024-12-01-18-10-30-590_com kiwibrowser browser dev-edit](https://github.com/user-attachments/assets/c48ba62d-9b59-4330-a0ca-fa0c163d7f10)

**Comment by possom2009** [comment]
> Which Chrome version are you using?

Kiwi Browser 124.0.6327.2

**Comment by hackademix** [comment]
> Kiwi Browser 124.0.6327.2

So it seems you (reporters on this bug) are both using this browser.

Is the version number on par with Chromium? Because it would explain your problems, since the `declarativeNetRequest.RuleCondition.responseHeaders` API is [available only on versions >= 128](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest#browser_compatibility)

Questions:

1. Was any of the previous 12.0.x versions working for you?
2. Is a Kiwi browser based on a recent Chromium available?

**Comment by C-O-D** [comment]
Question 1:
Since I have only had the problems for 2 or 3 days, I assume that one of the last versions still worked.
Question 2:
My Kiwi version is based on Chrome 124.0.6327.4 and unfortunately there is no newer Version

**Comment by possom2009** [comment]
> Question 1: Since I have only had the problems for 2 or 3 days, I assume that one of the last versions still worked. Question 2: My Kiwi version is based on Chrome 124.0.6327.4 and unfortunately there is no newer Version

Same here. Although my version of the browser isn't a dev build.

**Comment by C-O-D** [comment]
I have the same problem on the regular version. I only installed the developer version additionally because I need two separate installations.

**Comment by hackademix** [comment]
Please check if [12.0.8](https://noscript.net/getit/#nonstore-versions-for-chromium) fixes this issue, thanks.

**Comment by possom2009** [comment]
> Please check if [12.0.8](https://noscript.net/getit/#nonstore-versions-for-chromium) fixes this issue, thanks.

That one works. Everything seems to work now, no more blank pages.

**Comment by C-O-D** [comment]
Unfortunately I'm getting errors and pages don't load correctly.
![Screenshot_2024-12-02-13-21-43-813_com kiwibrowser browser dev-edit](https://github.com/user-attachments/assets/5072a29f-6141-4242-87a1-9f63717f7592)
![Screenshot_2024-12-02-13-22-26-367_com kiwibrowser browser dev-edit](https://github.com/user-attachments/assets/1b8bce18-d6e9-4e43-8c73-686fd1a2a442)

**Comment by hackademix** [comment]
> Unfortunately I'm getting errors and pages don't load correctly.

Those messages do not actually indicate any critical problem.

Could you provide more information about the pages not loading correctly?

Do they work correctly on [legacy version 11.4.44](https://noscript.net/getit/#nonstore-versions-for-chromium)?

**Comment by C-O-D** [comment]
e.g. duduckgo.com:
![Screenshot_2024-12-02-14-23-04-769_com kiwibrowser browser dev-edit](https://github.com/user-attachments/assets/3999cc90-b288-4c45-aee6-175c042db496)

Fehler
Error: Could not establish connection. Receiving end does not exist. Cannot collect noscript activity data at Object.collectSeen (chrome-extension://ijnkidnfkalopikbnpbiaejigkifnoln/bg/main.js:448:11) at async onActivatedTab (chrome-extension://ijnkidnfkalopikbnpbiaejigkifnoln/bg/RequestGuard.js:251:18)
Chrome is blocking ads on this site because this site tends to show ads that interrupt, distract, mislead, or prevent user control. You should fix the issues as soon as possible and submit your site for another review. Learn more at https://www.chromestatus.com/feature/5738264052891648
Uncaught (in promise) Error: Cannot access a chrome-extension:// URL of different extension
Chrome is blocking ads on this site because this site tends to show ads that interrupt, distract, mislead, or prevent user control. You should fix the issues as soon as possible and submit your site for another review. Learn more at https://www.chromestatus.com/feature/5738264052891648
Uncaught (in promise) ReferenceError: url is not defined

**Comment by hackademix** [comment]
@C-O-D are you're sure you're on 12.0.8?

**Comment by C-O-D** [comment]
> @C-O-D are you're sure you're on 12.0.8?

Absolutely
![Screenshot_2024-12-02-14-48-56-246_com kiwibrowser browser dev-edit](https://github.com/user-attachments/assets/3cd05c3d-54f0-4a76-956c-0ae6748c5045)

**Comment by C-O-D** [comment]
@hackademix But you know what in the course of all this action I realized how long there has been no update for Kiwi Browser and as it turns out the project is probably dead. So I'll have to find another browser anyway and until then I can live with using the legacy version 11 of no script. This new browser will most likely be a Firefox derivative of some kind, as I can't find any other Chrome-based browsers with extension support - and Firefox browsers are not affected by this problem here.
In any case, thank you very much for your spontaneous support which I really appreciate 👍

**Comment by hackademix** [comment]
> This new browser will most likely be a Firefox derivative of some kind

Yes, I strongly recommend Firefox for Android

> thank you very much for your spontaneous support which I really appreciate 👍

You're welcome ❤️

**Comment by C-O-D** [comment]
@hackademix Oops, would you mind briefly explaining why you recommend Firefox so highly for Android? Security-related reasons?

**Comment by hackademix** [comment]
> Oops, would you mind briefly explaining why you recommend Firefox so highly for Android? Security-related reasons?

- Actively developed
- Free and open source
- Many eyes on its security and privacy features, because it's the upstream for the Tor Browser for Android
- Extensions support far beyond  any Chromium derivative (see  https://noscript.net/usage/#limitations-on-chromium )
- Keeping Gecko alive helps the browser ecosystem not to become a stagnant Google-dependent monopoly

**Comment by C-O-D** [comment]
> > Oops, would you mind briefly explaining why you recommend Firefox so highly for Android? Security-related reasons?
> 
> * Actively developed
> * Free and open source
> * Many eyes on its security and privacy features, because it's the upstream for the Tor Browser for Android
> * Extensions support far beyond  any Chromium derivative (see  https://noscript.net/usage/#limitations-on-chromium )
> * Keeping Gecko alive helps the browser ecosystem not to become a stagnant Google-dependent monopoly

All right, that makes sense - thank you very much!

**Comment by possom2009** [comment]
Thanks for the quick response for this issue. Will the chrome store version be updated to 12.0.8 soon?

**Comment by hackademix** [comment]
> Will the chrome store version be updated to 12.0.8 soon?

Hard to say: I've submitted it this morning, at the same time as I've asked here to try its preview, but Chrome Store's review times are pretty unpredictable, ranging from hours to days or weeks. NoScript has an average of a couple days.

**Comment by possom2009** [comment]
> > Will the chrome store version be updated to 12.0.8 soon?
> 
> Hard to say: I've submitted it this morning, at the same time as I've asked here to try its preview, but Chrome Store's review times are pretty unpredictable, ranging from hours to days or weeks. NoScript has an average of a couple days.

Oh, ok. Thanks!
